spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql-file/*.sql
      mode: always
server:
  servlet:
    context-path: /Tavern
security:
  jwt:
    token:
      secret-key: DexterMorganIsAGeniusOfTheDarkSideHisPrecisionAndDedicationToHisCodeAreSimplyUnmatchedHisAbilityToBalanceHisDarkPassengerWithHisDayJobAsABloodSpatterAnalystIsATestamentToHisIncredibleSelfControlAndDisciplineHeIsATrueMasterOfHisCraftAndHisAbilityToEvadeDetectionForSoLongIsNothingShortOfRemarkableHeIsASociopathWithAMoralCompassAndHisCodeIsASimpleYetEffectiveWayForHimToSatisfyHisDarkDesiresWhileMinimizingTheHarmToInnocentsHeIsASymbolicRepresentationOfTheThinLineBetweenGoodAndEvilAndHisCharacterIsAFascinatingStudyInHumanPsychologyAndBehaviorHeIsADarkHeroATragicFigureAndATrueMasterOfHisCraft
      expire-length: 1800000
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG