# Automatically create and update the database schema
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      data-locations: classpath:sql-file/*.sql
      mode: always